install.packages("car")
install.packages("Hmisc")
install.packages("BSDA")
install.packages("reshape2")
install.packages("pgirmess")
install.packages("RCmdr")
library(car)
library(Hmisc)
library(BSDA)
library(reshape2)
library(pgirmess)
library(RCmdr)
fmily.wise.error <- 1-0.95^n
dset$factor <- factor(dset$factor)
t.test(dset$Age, mu = 75)
t.test(dset$Age[dset$Ticket == "1st"], mu = 75)
t.test(dset$Age, mu = 75, alternative = "g")
wilcox.test(dset$Age, mu = 75)
SIGN.test(dset$Age, md = 75)
levene.test(outcome.var, group, center = median)
var.test(dset$Age~dset$Fare.today)
shapiro.test(dset$Age)
shapiro.test(model$residuals)
t.test(dset$pulse~dset$Gender, var.equal = T)

summary(model.dset <- aov(dset$one~dset$two*dset$three))
plot(model.dset$residuals)
plot(model.dset, which = c(1,2,5))
model.tables(model.dset)
constasts(dset$two) <- "contr.helmert"
contrasts(dset$three) <- "contr.helmert"
coef(aov(dset$one~dset$two*dset$three))
oneway.test(dset$outcome~dset~predictor)
pairwise.t.test(dset$one, dset$two, pool.sd = FALSE, p.adjust.method = "none" )
kruskal.test(dset$one~dset$two)
kruskalmc(dset$one~dset$two)
aov(dset$one~dset$two, subset = (dset$three == 4))

acast(bottles,Carbonation.~Line.Speed,length,value.var="Deviation.from.Target")
dset <- melt(dset)
bartlett.test(dset$one, dset$two)
friedman.test(dset$one~dset$two|dset$three)
friedmanmc(dset$one, dset$two)
tuk <- TukeyHSD(dset.model)
plot(tuk)
interaction.plot(dset$one, dset$two, dset$three, col = c("red", "green"))

Davis[which.max(Davis$weight),]
davis <- davis[!(davis$weight==166),]
plot(y, x)
abline(y~x)
summary(model.lm <- lm(y~x, data = dset))
plot(model.lm)
dwt(model.lm)
mean(vif(model.lm))
vif(model.lm)
confint(model.lm,level=0.95)
predict(model.lm,data.frame(x=5),interval="confidence",level=0.95)
predict(model.lm,data.frame(x=5),interval="prediction",level=0.95)
model.log.lm <- lm(y~log(x), data = dset)
exp(predict(model.log.lm, data.frame(x=4), interval = "confidence", level = 0.95))