#week 4 companion code, bottles example
bottles <- read.csv("D:/University of Brighton/2016-2017 Data Analytics MSc/2016 MM705 - Multivariate Analysis and Statistical Modelling OPTIONAL SEM 2 20CR/Week 4 - Factorial Designs Continued; Multiple Comparisons/bottles.csv")
bottles$Carbonation. <- factor(bottles$Carbonation.,ordered=TRUE)
bottles$Operating.Pressure <- factor(bottles$Operating.Pressure,ordered=TRUE)
bottles$Line.Speed <- factor(bottles$Line.Speed,ordered=TRUE)
acast(bottles,Carbonation.~Operating.Pressure,length,value.var="Deviation.from.Target")
acast(bottles,Carbonation.~Line.Speed,length,value.var="Deviation.from.Target")
acast(bottles,Operating.Pressure~Line.Speed,length,value.var="Deviation.from.Target")
interaction.plot(bottles$Carbonation.,bottles$Operating.Pressure,bottles$Deviation.from.Target,trace.label="Pressure",xlab="CO2 %",ylab="Deviation",col=c("red","blue"))
interaction.plot(bottles$Carbonation.,bottles$Line.Speed,bottles$Deviation.from.Target,trace.label="Speed",xlab="CO2 %",ylab="Deviation",col=c("red","blue"))
interaction.plot(bottles$Operating.Pressure,bottles$Line.Speed,bottles$Deviation.from.Target,trace.label="Speed",xlab="Pressure",ylab="Deviation",col=c("red","blue"))
bottles.model <- aov(Deviation.from.Target~Carbonation.*Operating.Pressure*Line.Speed,data=bottles)
summary(bottles.model)
plot(bottles.model,which=c(1,2,5))
bottles.model.reduced <- aov(Deviation.from.Target~Carbonation.+Operating.Pressure+Line.Speed+Carbonation.:Operating.Pressure,data=bottles)
summary(bottles.model.reduced)
plot(bottles.model.reduced,which=c(1,2,5))
mean(bottles$Deviation.from.Target)
model.tables(bottles.model)
model.tables(bottles.model.reduced)
